services:
  - type: web
  env: node
  name: rabbit-hole
  repo: https://github.com/nozma-knows/rabbit-hole-backend
  buildCommand: yarn && yarn build
  startCommand: yarn start
  healthCheckPath: /
  envVars: 
    - key: DATABASE_URL
      fromDatabase:
        name: rabbit-hole-prod
        property: connectionString
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password
databases:
  - name: rabbit-hole-prod
    databaseName: rabbit-hole-prod
    user: rabbit_hole_prod_user
  